ARG BASE_IMAGE={{docker_illumidesk_notebook_base_image}}
FROM $BASE_IMAGE

ARG USER_ROLE=Instructor

USER $NB_UID

RUN jupyter nbextension enable --sys-prefix assignment_list/main --section=tree \
 && jupyter serverextension enable --sys-prefix nbgrader.server_extensions.assignment_list \
 && jupyter serverextension enable --sys-prefix nbgrader.server_extensions.course_list

WORKDIR /home/$NB_USER