ARG BASE_IMAGE={{docker_illumidesk_notebook_base_image}}
FROM $BASE_IMAGE

ARG USER_ROLE=Grader
ARG NB_UID=10001
ARG NB_USER=grader-{{course_id}}

USER $NB_UID

WORKDIR /home/$NB_USER

RUN jupyter nbextension enable --sys-prefix create_assignment/main \
 && jupyter nbextension enable --sys-prefix formgrader/main --section=tree \
 && jupyter serverextension enable --sys-prefix nbgrader.server_extensions.formgrader

# Copy customized formgrader files
COPY nbgrader/nbextensions/formgrader/main.js /opt/conda/lib/python3.7/site-packages/nbgrader/nbextensions/formgrader/main.js
COPY nbgrader/server_extensions/formgrader/templates/base.tpl /opt/conda/lib/python3.7/site-packages/nbgrader/server_extensions/formgrader/templates/base.tpl
