---
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
    language_version: python3.8

  - repo: https://github.com/ansible/ansible-lint.git
    sha: v3.3.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$