coverage:
  status:
    project:
      default: false
      tests:
        target: 100%
        paths: "src/tests/"
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
      app:
        target: auto
        threshold: 0%
        base: auto
        paths: 
          - "!src/tests/"
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
