#!/bin/bash

python3 -m pip install jupyter-server-proxy==1.5.0
jupyter serverextension enable --sys-prefix --py jupyter_server_proxy

cd theia

npm install yarn

npx yarn --cache-folder ./ycache && rm -rf ./ycache
export NODE_OPTIONS="--max_old_space_size=4096"
npx yarn theia build
npx yarn theia download:plugins
