ARG BASE_IMAGE={{docker_illumidesk_jhub_image}}
FROM ${BASE_IMAGE}

# Uninstall Python - Make sure before going for it
RUN apt purge remove python \
 && apt purge python3

# Refresh the packages index and install python3.8
RUN apt update \
 && add-apt-repository ppa:deadsnakes/ppa \
 && apt install python3.8

WORKDIR /usr/src/app
 
RUN python3 -m pip install --no-cache-dir \
    docker-compose \
    hypercorn

EXPOSE 8000

CMD ["hypercorn", "--bind", "0.0.0.0:8000", "--workers", "1", "illumidesk.setup_course.app:app"]

HEALTHCHECK CMD curl --fail http://localhost:8000/config || exit 1
