---
- name: create the nbgrader grader profile configuration file from template
  template:
    src: "grader_nbgrader_config.py.j2"
    dest: "{{ working_dir }}/grader_nbgrader_config.py"

- name: create the nbgrader grader course config from template
  template:
    src: "grader_course_nbgrader_config.py.j2"
    dest: "{{ working_dir }}/grader_course_nbgrader_config.py"

- name: copy the nbgrader global (learner/instructor) configuration file
  copy:
    src: "global_nbgrader_config.py"
    dest: "{{ working_dir }}/global_nbgrader_config.py"

- name: copy the grader's nbgrader config file to grader's host home directory
  template:
    src: "grader_nbgrader_config.py.j2"
    dest: "{{ mnt_root }}/{{ org_name }}/home/grader-{{ course_id }}/.jupyter/nbgrader_config.py"

- name: copy the course's nbgrader config file to grader's course host directory
  template:
    src: "grader_course_nbgrader_config.py.j2"
    dest: "{{ mnt_root }}/{{ org_name }}/home/grader-{{ course_id }}/{{ course_id }}/nbgrader_config.py"

- name: change nbgrader's nbconfig permissions
  file:
    path: "{{ mnt_root }}/{{ org_name }}/home/grader-{{ course_id }}/.jupyter/nbgrader_config.py"
    owner: "10001"
    group: "100"

- name: change nbgrader's nbconfig course permissions
  file:
    path: "{{ mnt_root }}/{{ org_name }}/home/grader-{{ course_id }}/{{ course_id }}/nbgrader_config.py"
    owner: "10001"
    group: "100"

- name: create nbgrader target directory
  file:
    path: "{{ working_dir }}/nbgrader/nbextensions/formgrader"
    state: directory
    mode: 0755

- name: create nbgrader target directory
  file:
    path: "{{ working_dir }}/nbgrader/server_extensions/formgrader/templates"
    state: directory
    mode: 0755

- name: copy formgrader nbextension js
  copy:
    src: "nbextensions/formgrader/main.js"
    dest: "{{ working_dir }}/nbgrader/nbextensions/formgrader/main.js"

- name: copy formgrader server extension template
  copy:
    src: "server_extensions/formgrader"
    dest: "{{ working_dir }}/nbgrader/server_extensions"
