FROM {{docker_illumidesk_notebook_base_image}}

ARG R_VERSION=3.6.1
ARG RSTUDIO_VERSION=1.3.959

ENV DISABLE_AUTH=true
ENV R_VERSION=$R_VERSION
ENV RSTUDIO_VERSION=$RSTUDIO_VERSION
ENV PATH=/usr/lib/rstudio-server/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib/R/lib
ENV R_HISTFILE=".Rhistory"
ENV XDG_CONFIG_HOME=$HOME/.config/rstudio
ENV XDG_CONFIG_DIRS=/etc/rstudio

USER root

RUN sed -i.bak "/^#.*deb-src.*universe$/s/^# //g" /etc/apt/sources.list \
 && apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y \
    dirmngr \
    file \
    gdebi-core \
    gnupg \
    libapparmor1 \
    libclang-dev \
    libcurl4-openssl-dev \
    libedit2 \
    libopenblas-dev \
    libx11-dev \
    lsb-release \
    multiarch-support \
    procps \
    psmisc \
    r-base \
    r-base-dev \
    xorg-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# R
RUN wget -q "https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-${R_VERSION}_1_amd64.deb" \
 && gdebi "r-${R_VERSION}_1_amd64.deb" \
 && ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/R \
 && ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/Rscript \
 && rm -f "r-${R_VERSION}_1_amd64.deb"

# Setup RStudio global config directory
RUN mkdir -p $XDG_CONFIG_DIRS \
 && mkdir -p $XDG_CONFIG_HOME \
 && chown -Rf $NB_UID:$NB_GID $XDG_CONFIG_HOME

# RStudio
RUN wget -q "http://download2.rstudio.org/server/bionic/amd64/rstudio-server-${RSTUDIO_VERSION}-amd64.deb" \
 && gdebi "rstudio-server-${RSTUDIO_VERSION}-amd64.deb" \
 && dpkg -i rstudio-server-*-amd64.deb \
 && ln -s /usr/lib/rstudio-server /usr/local/lib/rstudio-server \
 && rm  "rstudio-server-${RSTUDIO_VERSION}-amd64.deb" \
 && echo "www-frame-origin=any" >> $XDG_CONFIG_DIRS/rserver.conf \
 && echo "auth-proxy=1" >> $XDG_CONFIG_DIRS/rserver.conf \
 && echo "r-cran-repos=http://cran.us.r-project.org" >> $XDG_CONFIG_DIRS/rserver.conf \
 && chown $NB_UID:$NB_GID $XDG_CONFIG_DIRS/rserver.conf

USER $NB_USER

WORKDIR $HOME

# install rsession-proxy and other python packages if needed
COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt \
 && rm requirements.txt

# https://docs.rstudio.com/ide/server-pro/1.3.820-1/r-sessions.html#user-preferences
COPY rstudio-prefs.json $XDG_CONFIG_HOME/rstudio-prefs.json
