name: Build, test, and publish Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "src/illumidesk/**"
      - "src/illumideskdummyauthenticator/**"
      - "src/graderservice/**"
      - "Makefile"
      - "pytest.ini"
      - "dev-requirements.txt"

  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "src/illumidesk/**"
      - "src/illumideskdummyauthenticator/**"
      - "src/graderservice/**"
      - "Makefile"
      - "pytest.ini"
      - "requirements-dev.txt"

jobs:
  build-test-publish-images:
    name: Build, test, and publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          make -C main dev

      - name: Build Docker Images
        run: make -C main build-hubs-k8
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Build Docker Images
        run: make -C main build-hubs
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Build Docker Images
        run: make -C main build-grader-setup-service
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Run Post-Build Hooks
        id: hook-all
        run: make -C main hook-all

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/main'
        run: make -C main push-all
