name: Build, test, and publish Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "src/illumidesk/**"
      - "src/illumideskdummyauthenticator/**"
      - "src/graderservice/**"
      - "Makefile"
      - "pytest.ini"
      - "dev-requirements.txt"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "src/illumidesk/**"
      - "src/illumideskdummyauthenticator/**"
      - "src/graderservice/**"
      - "Makefile"
      - "pytest.ini"
      - "requirements-dev.txt"

jobs:
  build-test-publish-images:
    name: Build, test, and publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          make -C main dev
      - name: Build Docker Images
        run: make -C main build-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Test Docker Images
        run: make -C main test-all

      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Run Post-Build Hooks
        id: hook-all
        run: make -C main hook-all

      - name: Push Wiki to GitHub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc # dependabot updates to latest release
        with:
          commit_message: "Automated publish for ${{github.sha}}"
          repository: wiki/

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: make -C main push-all-multi