name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-hooks:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    strategy:
      # Keep running even if one job fails
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"

    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pre-commit
        run: make -C main dev

      - name: Run pre-commit hooks
        run: make -C main pre-commit-all
