name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue has been tagged as stale due to inactivity'
        stale-pr-message: 'This pull has been tagged as stale due to inactivity'
        stale-pr-label: 'stale'
        days-before-stale: 90
        days-before-close: 7
