ARG BASE_IMAGE={{docker_jhub_base_image}}
FROM ${BASE_IMAGE}

# add additional packages for postgres
RUN apt-get update \
 && apt-get install -yq --no-install-recommends \
    apt-utils \
    fonts-liberation \
    git \
    libpq-dev \
    nano \
    postgresql-client \
    software-properties-common \
    sudo \
    wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# always make sure pip is up to date!
RUN python3 -m pip install --no-cache --upgrade setuptools pip

# Enable prompt color in the skeleton .bashrc before creating the default JH_USER
# TODO: add steps to add JH_USER and run the jhub with this user
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc

WORKDIR /tmp

# Install packages from requirements file
COPY jupyterhub-requirements.txt /tmp/jupyterhub/requirements.txt
RUN python3 -m pip install --no-cache -r /tmp/jupyterhub/requirements.txt

# Install illumidesk package
COPY illumidesk.zip /tmp/illumidesk.zip
RUN python3 -m pip install --no-cache /tmp/illumidesk.zip

# Copy logo and favicon
COPY illumidesk-80.png /usr/local/share/jupyterhub/static/images/illumidesk-80.png
COPY favicon.ico /usr/local/share/jupyterhub/static/favicon.ico

# Copy templates
COPY share/templates/. /usr/local/share/jupyterhub/templates/.

# /etc/jupyterhub/jupyterhub_config.py by default
COPY jupyterhub_config.py /etc/jupyterhub/jupyterhub_config.py

WORKDIR /srv/jupyterhub

# Get announcement from jupyterhub examples folder
RUN wget https://raw.githubusercontent.com/jupyterhub/jupyterhub/d126baa443ad7d893be2ff4a70afe9ef5b8a4a1a/examples/service-announcement/announcement.py

# Copy postgres util script and update permissions
COPY wait-for-postgres.sh /srv/jupyterhub/wait-for-postgres.sh
RUN chmod +x /srv/jupyterhub/wait-for-postgres.sh

# Run standard command but wait for postgres
# https://docs.docker.com/compose/startup-order/
CMD ["/srv/jupyterhub/wait-for-postgres.sh", "python3", "jupyterhub", "-f", "/etc/jupyterhub/jupyterhub_config.py"]

HEALTHCHECK CMD curl --fail http://localhost:8081/ || exit 1
